# Generated by Django 2.1.3 on 2018-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Employee_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=45, null=True)),
                ('Email_ID', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
