# Generated by Django 2.1.3 on 2018-12-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='User_Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
